name: ExemplePlugin
main: com.plugin.exemple.Exemple
version: 0.1
commands:
   exemple:
      description: Informations sur le plugin.
      usage: /<command>
   getPet:
      description: Donne un oeuf permettant de faire aparaitre un pet.
      usage: /<command>
      
   spawncow:
      description: Fais pop une vache sur nous.
      usage: /<command>